version: '3'
services:

  mysql:
   image: mysql:5.5
   network_mode: host
   restart: always
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: moviedb

  spring:
   image: rishabhchadha/moviecruiser:spring-image
   restart: always
   network_mode: host
   ports:
     - "8082:8082"
   expose:
     - "8082"
   depends_on:
     - mysql
  
  angular:
    image: rishabhchadha/moviecruiser:angular-image
    network_mode: host
    container_name: angular-docker
    ports:
      - "4200:4200"

